# Source: ghost/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: example/mariadb
  name: mariadb
  namespace: example
  labels:
    app.kubernetes.io/name: mariadb
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|example|mariadb'
automountServiceAccountToken: false
